name: Yframe
api:
- 3.0.0
- 4.0.0
version: '1.0.0_alpha'
load: POSTWORLD
main: yxmingy\Yframe\Main
author: xMingcommands:
  Yframe:
    description: "主指令"
    permission: yxmingy.yframe.command
    usage: "/hs [obj]"
permissions:
  yxmingy.yframe.command: 
    default: op
